contact_links:
  - name: First name
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: Second Name
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
